name: Test Failure Handling

on:
  workflow_dispatch:

jobs:
  will-fail:
    runs-on: ubuntu-latest
    
    steps:
      - name: This will succeed
        run: echo "Success!"
      
      - name: This will fail
        run: exit 1
      
      - name: This won't run
        run: echo "You won't see this"